namespace Utilities.Audio
{
    public enum AudioNameEnum
    {
        BASHER_ATTACK,
        BASHER_IDLE,
        DOOR_OPEN,
        DOOR_CLOSE,
        PLAYER_HIT,
        SOUND_TRACK,
        PLAYER_DIE,
        PLAYER_STEP,
        BASHER_STEP,
        BASHER_SCREAM,
        PLAYER_HEARTBEAT,
        ITEM_PICKUP,
        ITEM_SUIT_PICKUP,
        ITEM_LANTERN_PICKUP,
        ITEM_LANTERN_PICKUP_DENIED,
        ITEM_LANTERN_CLICK,
        GENERATOR_MINIGAME_SELECT,
        GENERATOR_MINIGAME_FAILED,
        GENERATOR_MINIGAME_SUCCESS,
        GENERATOR_ACTIVACTION,
        GENERATOR_EXPLOSION
    }
}